version: '3.8'

services:
  app:
    build:
      context: .
    container_name: labLogTransform
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: appuser
      DATABASE_PASSWORD: password
      DATABASE_NAME: postgres
    depends_on:
      - db
    volumes:
      - .:/app
      - ./uploads:/app/uploads 
  db:
    image: postgres
    container_name: db-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: