FROM node:20.19.0

WORKDIR /usr/src/app

# Copiando dependências
COPY package*.json ./
RUN npm install

# Copiando o resto do código
COPY . .

# Build do projeto (se estiver usando TypeScript)
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]